### ISSUE TITLE
mention breaking changes in readme file

### ISSUE THREAD

**Issue by saarangsoltani** [cibernox/ember-cli-accounting#10]
A lot of people don't use HtmlBars yet  and its causes confusion as to why the addon is throwing errors. I think it should clearly be mentioned on the readme file that if you are not on the latest ember you must pull in the '0.0.4' version of the addon. I was about to uninstall the addon but i was lucky to take a look at changelog at the very last minute.

**Comment by cibernox** [comment]
It is already mentioned in the install section of the readme: https://github.com/cibernox/ember-cli-accounting#installation

In any case, if you had trouble to see it, anyone else might have too. I'll make it more visible.
