### ISSUE TITLE
Define global options

### ISSUE THREAD

**Issue by dennisver** [cibernox/ember-cli-accounting#11]
It would be nice to have a way to define global options, so it's possible to use a helper multiple times without passing the same attributes multiple times.

**Comment by cibernox** [comment]
It is possible, using by example an initializer. I added an entry on the readme explaining how to do it.

Per example, if your app is used in Spain, you probably want an initializer like this:

```js
import { currency, number } from "accounting/settings";

export default {
  name: 'accounting.js',
  initialize: function() {
    currency.symbol = "€";
    number.decimal = ",";
    number.thousand = ".";
  }
};
```

You could also make some kind of ajax call to get the user's preferences in that initializer, and defer the readiness of the app until the ajax call finalizes.

Hope this explanation helps.

**Comment by dennisver** [comment]
Works fine, thank you!
