### ISSUE TITLE
HTMLBars helper registration deprecation

### ISSUE THREAD

**Issue by engwan** [cibernox/ember-cli-accounting#15]
Using `Ember.HTMLBars.makeBoundHelper` is deprecated. Please refactor to using `Ember.Helper` or `Ember.Helper.helper`. [deprecation id: ember-htmlbars.make-bound-helper]

**Comment by cibernox** [comment]
I'm aware. I'll put this in my calendar to some point this week.

**Comment by MichaelVdheeren** [comment]
+1

**Comment by MichaelVdheeren** [comment]
https://github.com/cibernox/ember-cli-accounting/pull/16

**Comment by cibernox** [comment]
Just released this as version 1.0.0

Now that ember has a stable Helper API and autoregistration this can be considered stable. Only compatible with ember 1.13 and 2.0+
