### ISSUE TITLE
$0 rendered as $--

### ISSUE THREAD

**Issue by mmahalwy** [cibernox/ember-cli-accounting#18]
Is there a way to use `format-money` and have $0 render as $0 ad not $--? 

Thanks!

**Comment by cibernox** [comment]
Sorry, I probably missed this 6 months ago while on holidays and when I went back I declared github notifications bankruptcy.

I think that accounting.js can do that, but I'm no expert. Probably the docs can help: http://openexchangerates.github.io/accounting.js/
