### ISSUE TITLE
Add ability pass custom formatters ( as functions ) to add additional formats

### ISSUE THREAD

**Issue by vvscode** [cibernox/ember-cli-accounting#19]
What about adding ability pass functions which implements custom formats? 

or PR is welcome? )

**Comment by cibernox** [comment]
This addons is just a port of the accounting.js library, so I don't want to augment it's public API in any way. 
If any new feature gets implemented in accounting I'll be happy of porting it here too. 

That said, accounting.js allows custom formats. Maybe that is enough for what you want.
