### ISSUE TITLE
typed-ember included in 2.0.0 revision of package

### ISSUE THREAD

**Issue by NLincoln** [cibernox/ember-cli-accounting#27]
This is a weird one... 

# Repro
1. Download `ember-cli-accounting@2.0.0` directly from the yarn registry via `wget https://registry.yarnpkg.com/ember-cli-accounting/-/ember-cli-accounting-2.0.0.tgz`
1. `tar xvf ember-cli-accounting-2.0.0.tgz`
1. `cd package`

There should be a `typings/ember` folder
As best as I can tell, the typings included are from https://github.com/wagenet/typed-ember, but they aren't part of the git sourcetree for this addon. 

While my instructions above use yarn, the bug also occurs with npm.

**Comment by cibernox** [comment]
Fixed.

That folder is created by vscode to have typescript-like information on packages authored in JS. It was on my global .gitignore but not in the .npmignore
