### ISSUE TITLE
Format-number with precision 0 for -0.2 is -0

### ISSUE THREAD

**Issue by lakhanbaheti** [cibernox/ember-cli-accounting#30]
{{format-number  -0.2 decimal='.' thousand=',' precision=0}}

Here Output is -0

But I want is only 0

**Comment by cibernox** [comment]
This addon is just a port of accounting.js, nothing more. 
Can you check if accounting.js itself has this bug and report it if it does? If that's the case, it has to be fixed in accounting.js first

**Comment by lakhanbaheti** [comment]
Same issue has been reported in accounting.js - 

https://github.com/openexchangerates/accounting.js/issues/174

**Comment by cibernox** [comment]
In that case we'll have to wait until it's fixed there and then backport the fix
