### ISSUE TITLE
Format Money incorrectly formats negative values

### ISSUE THREAD

**Issue by hbrysiewicz** [cibernox/ember-cli-accounting#35]
Typically when writing a money value in USD that is negative (I'm not sure about other currencies), one would write "-$100,00.23" however this library does not allow for the detailed formatting necessary for this to work. While one could provide the ordering for "%v" value and "%s" symbol, there is no way to specify where the sign should go. 

For now, I have worked around this by using a combination of this library with the [ember-math-helpers](github.com/shipshapecode/ember-math-helpers). 

```
{{if (lt value 0) '-'}}{{format-money (abs value) precision=2}}
```

**Comment by cibernox** [comment]
Can you verify if this is a bug in accounting.js itself? I made this addon as a port, so I want to be sure it's a but *I* introduced and it's not in the original codebase

**Comment by hbrysiewicz** [comment]
It isn't a bug, really. Its just a limitation of this package. When formatting in `format-money`, which in turn uses `format-number` there is no ability to specify the sign position. 

[Line 59](https://github.com/cibernox/ember-cli-accounting/blob/master/addon/format-number.js#L59) in `format-number` shows that the sign is being included in this step which makes it impossible for anything that uses `format-number` (like `format-money`) to be more specific about where the sign should go.

Ideally one could specify format [as outlined in `format-money`](https://github.com/cibernox/ember-cli-accounting/blob/master/addon/format-money.js#L37) with an additional parameter to denote signage. "%n" perhaps (for negative)?

**Comment by cibernox** [comment]
> I see what you're saying, that this is a port of accounting.js and they don't provide that functionality so this library should not either?

Probably no. 

However I have to say that I don't use this library anymore because I'm using `ember-intl`, which uses the native `Intl` API in the browser (available in pretty much every browser: https://caniuse.com/#feat=internationalization)

If your browser matrix supports it, it's the best way of localizing ANYTHING: money, time, dates, durations.... you name it.

**Comment by hbrysiewicz** [comment]
Oh, nice! Thanks! I'll check it out.
